[project]
channels = ["conda-forge", "bioconda"]
name = "comebin_cuda"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
comebin = "1.0.4"
checkm-genome = "1.1.3"
pytorch-gpu = "*"
gawk = "*"

[system-requirements]
cuda = "12.6"