title: "IKMB TOFU-MAaPO QC report"
subtitle: "Best-practice metagenome pipeline"
custom_logo: "ikmblogo.png"
custom_logo_title: "Insitute of Clinical Molecular Biology, Kiel"
custom_logo_url: "http://www.ikmb.uni-kiel.de"

extra_fn_clean_exts:
  - "_R1"
  - "_R2"
  - "_L001"
  - "_L002"
  - ".R1"
  - ".R2"
  - "_raw"
  - "_L003"
  - "_L004"
  - "_1"
  - "_2"

report_comment: >
    This report has been generated automatically by the IKMB TOFU-MAaPO pipeline.

report_header_info:
    - Contact E-mail: "e.wacker@ikmb.uni-kiel.de"
    - Application Type: "Nextflow Pipeline github.com/ikmb/TOFU-MAaPO"

top_modules:
- 'fastqc':
    name: 'FastQC: raw reads'
    path_filters_exclude:
        - '*clean*'
        - '*trimmed'
- 'fastqc':
    name: 'FastQC: after QC'
    info: 'Reads after trimming and, if requested, host removal.'
    path_filters:
        - '*clean*'
        - '*trimmed'
- 'fastp':
    name: 'fastp'
    info: 'Fastp quality control'