FROM nvidia/cuda:12.3.1-base-ubuntu22.04
#FROM ubuntu:latest
LABEL authors="Eike Matthias Wacker" \
      description="Docker image containing all requirements for recent version of gpu capable vamb for metagenome-pipeline"
      
# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
# Install python
RUN apt-get update && apt-get install -y python3-dev python3-pip python3-opencv git gawk python-is-python3 libglib2.0-0
# Update pip
RUN python3 -m pip install --upgrade pip
# Install vamb and its dependencies with pip
RUN pip install torch torchvision vamb --no-cache-dir  && pip install vamb==4.1.3 pycoverm --force-reinstall --use-deprecated=legacy-resolver
